DROP TABLE IF EXISTS LOCATION;
CREATE TABLE LOCATION (
  LOC_ID INTEGER PRIMARY KEY ASC,
  LOC_LAT FLOAT NOT NULL,
  LOC_LONG FLOAT NOT NULL,
  LOC_ADDR VARCHAR(256) NOT NULL,
  LOC_NAME VARCHAR(64) NOT NULL,
  LOC_DESC VARCHAR(256) DEFAULT NULL
);

INSERT INTO LOCATION (LOC_LAT, LOC_LONG, LOC_ADDR, LOC_NAME) VALUES (43.0769654,-87.8831759,'2131 East Hartford Avenue, Milwaukee Wisconsin 53211', 'UWM SARUP');

DROP TABLE IF EXISTS MONITOR;
CREATE TABLE MONITOR (
  MON_ID INTEGER PRIMARY KEY ASC,
  LOC_ID INTEGER NOT NULL REFERENCES LOCATION(LOC_ID),
  MON_NAME VARCHAR(64) NOT NULL
);

DROP TABLE IF EXISTS FACADE;
CREATE TABLE FACADE (
  FCD_ID INTEGER PRIMARY KEY ASC,
  FCD_NAME VARCHAR(64) NOT NULL,
  FCD_DESC VARCHAR(256) DEFAULT NULL
);

INSERT INTO FACADE (FCD_NAME, FCD_DESC) VALUES ('Tempered Glass', 'Default facade');

DROP TABLE IF EXISTS PIEZO;
CREATE TABLE PIEZO (
  PIEZO_ID INTEGER PRIMARY KEY ASC,
  MON_ID INTEGER NOT NULL REFERENCES MONITOR(MON_ID),
  FCD_ID INTEGER NOT NULL REFERENCES FACADE(FCD_ID),
  PIEZO_PIN_ID INTEGER NOT NULL,
  PIEZO_NAME VARCHAR(64) NOT NULL,
  PIEZO_DIR CHAR(2) NOT NULL,
  PIEZO_MIN FLOAT NOT NULL,
  PIEZO_MAX FLOAT NOT NULL,
  CONSTRAINT unique_pin_mon_tuple UNIQUE( MON_ID, PIEZO_PIN_ID ) ON CONFLICT REPLACE
);

DROP TABLE IF EXISTS COLLISION;
CREATE TABLE COLLISION (
  COLL_ID INTEGER PRIMARY KEY ASC,
  PIEZO_ID INTEGER NOT NULL REFERENCES PIEZO(PIEZO_ID),
  COLL_EST_EL FLOAT NOT NULL,
  COLL_WAVE VARCHAR(512) NOT NULL,
  COLL_TSTAMP DATETIME NOT NULL
);
